CREATE TABLE blogful_articles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    content TEXT
);

--Note: We are now using the TIMESTAMPTZ type which is shorthand for TIMESTAMP WITH TIME ZONE. This forces all timestamp entries to be recorded in UTC time, which removes ambiguities and improves reliability with our tests.--
